### PR TITLE
Update table of contents and remove repeated pulumi

### PR DESCRIPTION
**Pull request by kbelokon**

### CODE REVIEW

**Comment by seifrajhi** [comment]
Thank you very much @kbelokon, can we enhance by adding some action to automate this lint typos 🤔

**Comment by kbelokon** [comment]
Oh, this is interesting! We can use [markdownlint](https://github.com/igorshubovych/markdownlint-cli). I've written a custom rule for it that catches duplicates within the same section. 
I did it within the same section because, for example, `Better Stack` appears several times in different sections, and I think that's normal behavior and we don't want to count it as duplicates.
We can set up a GitHub action on pull requests that will go through the README.md and fail if something is wrong.

```javascript
module.exports = {
    "names": ["detect-duplicates-in-section"],
    "description": "Rule that reports duplicate links within the same section",
    "tags": ["links"],
    "function": function rule(params, onError) {
        let linksInSection = new Map();
        let currentHeading = null;

        params.tokens.forEach(token => {
            if (token.type === 'heading_open') {
                currentHeading = token.lineNumber;
                linksInSection.clear();
            } else if (token.type === 'inline' && currentHeading) {
                token.children.filter(child => child.type === 'link_open').forEach(link => {
                    const href = link.attrGet('href');
                    const text = token.content;
                    if (linksInSection.has(href) && linksInSection.get(href) === text) {
                        onError({
                            lineNumber: link.lineNumber,
                            detail: `Duplicate link in section starting at line ${currentHeading}: [${text}](${href})`
                        });
                    } else {
                        linksInSection.set(href, text);
                    }
                });
            }
        });
    }
};
```

**Comment by seifrajhi** [comment]
> Oh, this is interesting! We can use [markdownlint](https://github.com/igorshubovych/markdownlint-cli). I've written a custom rule for it that catches duplicates within the same section. I did it within the same section because, for example, `Better Stack` appears several times in different sections, and I think that's normal behavior and we don't want to count it as duplicates. We can set up a GitHub action on pull requests that will go through the README.md and fail if something is wrong.
> 

Looks very cool idea, can you test it in your branch, if it works we can add it to the repo ?

**Comment by kbelokon** [comment]
Easy, I'll do it today or tomorrow

**Comment by kbelokon** [comment]
Works for me in [PR](https://github.com/kbelokon/awesome-platform-engineering-tools/actions/runs/7737434815/job/21096413274). I made it so that it only checks in PR and only when .md files are changed. Do you think that's okay, or do we want to see a failed action when you push to the main branch?

**Comment by seifrajhi** [comment]
Yes ideally, it should block from merging to main if it fails and to see the failed error
What do you think ?

**Comment by seifrajhi** [comment]
Perfect @kbelokon  💯 🥇

**Pull request merged**
